language: php

php:
  - '7.1'

before_script:
  - composer self-update
  - composer install --prefer-source --dev

script: phpunit --coverage-text --colors=never

notifications:
    on_success: never
    on_failure: always