language: php

php:
  - '7.1'

sudo: required

services:
  - docker

compiler:
  - clang
  - g++

before_install:
  - composer require php-coveralls/php-coveralls

before_script:
  - composer self-update
  - composer install --prefer-source --dev
  - docker run -p 9000:9000 -p 8123:8123 -d --name some-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server
  - cd utils/ccat
  - make && make install
  - cd ../../

script: phpunit --coverage-php coverage/coverage.cov

after_success:
 - php vendor/bin/php-coveralls -v

notifications:
    on_success: never
    on_failure: always
